@startuml
Interface Subject{
	+register()
	+unregister()
	+notifyObservers()
	+getUpdate()
}
Interface Observer{
	+update()
	+setSubject()
}
class MyTopic{
	-observers: List<Observer>
	-message: String
	-changed: boolean
	-MUTEX: Object
	+register()
	+unregister()
	+notifyObservers()
	+getUpdate()
	+postMessage()
}
class MyTopicSubscriber{
	-name: String
	-topic: Subject
	+update()
	+setSubject()
}
MyTopicSubscriber --> Subject
MyTopicSubscriber .up.|> Observer
MyTopic --> Observer
MyTopic .up.|> Subject
@enduml
