@startuml
title Class diagram
class Estudiante{
	-codigo: String
	-correo: String
	-nombre: String
	-apellido: String
	-carreraEstudiante: Carrera
	-gruposEstudiante: List<Grupo>
	-notasEstudiante: List<Nota>
	+darCodigo()
	+cambiarCodigo()
	+darCorreo()
	+cambiarCorreo()
	+darNombre()
	+cambiarNombre()
	+darApellido()
	+cambiarApellido()
	+darCarrera()
	+cambiarCarrera()
	+darGrupos()
	+cambiarGrupos()
	+darNota()
	+cambiarNotas()
	+toString()
}
class Carrera{
	-nombre: String
	+facultadCarrera: Facultad
	#departamento: String
	-{static}nuevoListaEstudiantes: List<Estudiante>
	+darFacultad()
	+cambiarFacultad()
	+darDepartamento()
	+cambiarDepartamento()
	-{static}darNombre()
	#cambiarNombre()
	+darEstudiantes()
	+cambiarEstudiantes()
	+toString()
}
Carrera o-- Estudiante
Estudiante o-- Carrera
@enduml
