@startuml
title forEach
start
:New list: <b>words</b>;
:Assign <color:darkblue><i>newArrayList<>()</i></color> to <b>words</b>;
:words.add("hello");
:words.add("world");
while(For each <b>word</b> of <b>words</b>);
:Print: <color:darkblue><i>word</i></color>;
endWhile (No more elements)
stop
@enduml
