@startuml
title main
start
:New object: <b>ob</b>;
:Assign <color:darkblue><i>newBubbleSort()</i></color> to <b>ob</b>;
:New array: <b>arr</b>;
:Assign <color:darkblue><i>{64,34,25,12,22,11,90}</i></color> to <b>arr</b>;
:Enter subroutine: <color:darkred><b>bubbleSort</b></color>;
:Print: <color:darkblue><i>"Sorted array"</i></color>;
:Enter subroutine: <color:darkred><b>printArray</b></color>;
stop
@enduml
